# Generated by Django 6.0.3 on 2026-09-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_import',
            field=models.BooleanField(default=False, help_text='Show this vehicle in the Import cars collection.'),
        ),
    ]
